version: "3.9"

networks:
  app_network:
    driver: bridge

services:

  postgres:
    image: postgres:16
    command: >
      bash -c "chmod +x /docker-entrypoint-initdb.d/02-init-n8n-db.sh && docker-entrypoint.sh postgres"
    container_name: postgres_db
    restart: always
    networks:
      - app_network
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: SGPasswordPostgres
      POSTGRES_DB: panel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./postgres/init-n8n-db.sh:/docker-entrypoint-initdb.d/02-init-n8n-db.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d panel" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    networks:
      - app_network
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sgtech.tech
      PGADMIN_DEFAULT_PASSWORD: SGPasswordPostgres
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    networks:
      - app_network
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: admin
      DB_POSTGRESDB_PASSWORD: SGPasswordPostgres
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: admin123
      N8N_HOST: 0.0.0.0
      N8N_PORT: 5678
      N8N_PROTOCOL: http
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    networks:
      - app_network
    ports:
      - "8000:8000"
    volumes:
      - ./laravel:/var/www/html
      - laravel_vendor:/var/www/html/vendor
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: panel
      DB_USERNAME: admin
      DB_PASSWORD: SGPasswordPostgres
    depends_on:
      postgres:
        condition: service_healthy

  angular:
    build:
      context: ./angular
      dockerfile: Dockerfile
    container_name: angular_app
    networks:
      - app_network
    ports:
      - "4200:4200"
    volumes:
      - angular_node_modules:/app/node_modules
      - ./angular:/app

volumes:
  postgres_data:
  n8n_data:
  laravel_vendor:
  angular_node_modules:
