name: Deploy Frontend and Backend to Cloud Run

on:
  push:
    branches:
      - Deployment

env:
  PROJECT_ID: panel-sgtech-20260603
  REPO_NAME: panel-docker
  REGION: us-central1

jobs:
  # ─── SERVICIO 1: ANGULAR (FRONTEND) ───
  deploy-angular:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and Push Angular
      run: |
        IMAGE_URL=us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/panel-frontend:latest
        docker build -t $IMAGE_URL -f ./EntornoDesarrollo/angular/Dockerfile ./EntornoDesarrollo/angular
        docker push $IMAGE_URL

    - name: Deploy Angular to Cloud Run
      run: |
        gcloud run deploy panel-frontend \
          --image us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/panel-frontend:latest \
          --region ${{ env.REGION }} \
          --platform managed \
          --port 8080 \
          --allow-unauthenticated

  # ─── SERVICIO 2: LARAVEL (BACKEND) ───
  deploy-laravel:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and Push Laravel
      run: |
        IMAGE_URL=us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/panel:latest
        docker build -t $IMAGE_URL -f ./EntornoDesarrollo/laravel/Dockerfile ./EntornoDesarrollo/laravel
        docker push $IMAGE_URL

    - name: Deploy Laravel to Cloud Run
      run: |
        gcloud run deploy panel \
          --image us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/panel:latest \
          --region ${{ env.REGION }} \
          --platform managed \
          --port 8080 \
          --timeout 600 \
          --allow-unauthenticated
